name: Create a release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version name. example v0.1.1"
        required: true

jobs:
  bump-version:
    uses: ./.github/workflows/tag-components.yml
    with:
      tag: ${{ github.event.inputs.version }}

  publish-component-image:
    name: Publish flyte component image for the release version
    runs-on: ubuntu-latest
    needs: [bump-version]
    strategy:
      matrix:
        component:
          [
              abc,
              def,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Get Latest Version of component
        id: set_version
        run: |
          if [ ${{ matrix.component }} = "abc" ]; then
            echo "bla"
          elif [ ${{ matrix.component }} != "abc" ]; then
            echo "ble"
          else
            echo "blu"
          fi
        shell: bash
