name: Create a release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version name. example v0.1.1"
        required: true

jobs:
  tag-components:
    uses: ./.github/workflows/tag-components.yml
    with:
      tag: ${{ github.event.inputs.version }}

